# Site settings
title: Kan Chen
header-img: img/home-bg.jpg
email: chenkan0007@gmail.com
description: "Welcome to Kan Chen's personal website!"
baseurl: ""
url: "http://wind09.github.io"
twitter_username: chenkan0007
github_username:  wind09
linkedin_username:  pub/kan-chen/57/4b9/52

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems: [jekyll-paginate]